@base_address = http://localhost:3000/api/people

POST {{base_address}}
Content-Type: application/json

{
    "firstName":"Jimmy",
    "lastName":"Doe"
}

###
GET {{base_address}}

###
PUT {{base_address}}/3
Content-Type: application/json

{
    "id":3,
    "firstName":"Updated",
    "lastName":"Name"
}

###
DELETE {{base_address}}/2
