name: Deploy to Amazon Lambda

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
        
 

env:
  BUCKET_NAME: arn:aws:s3:::react-dotnet-frontend-bucket
  AWS_REGION: us-east-1


permissions:
  id-token: write
  contents: read

jobs:
  LambdaPackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v6
        
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6.2.4
        with:
          role-to-assume: arn:aws:iam::819352519261:role/github-actions-oidc-role
          role-session-name: awsLambdaBackendDeploySession
          aws-region: us-east-1

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Restore and build
        run: |
          cd ${{ github.workspace }}/Backend/Backend
          dotnet restore
          dotnet build --configuration Release
          
      - name: Install lambda tools
        run: |
          cd ${{ github.workspace }}/Backend/Backend
          dotnet tool install -g Amazon.Lambda.Tools

      - name: Deploy to S3
        run: |
          cd ${{ github.workspace }}/Backend/Backend
          dotnet lambda deploy-function dotnet-backend-lambda-test --project-location .
 
